// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"demo/internal/biz"
	"demo/internal/data"
	"demo/internal/service"
	"demo/pkg/cache/redis"
	"demo/pkg/database/sql"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	db := sql.NewMySQL()
	redisRedis := redis.NewRedis()
	userRepo := data.New(db, redisRedis)
	userUseCase := biz.New(userRepo)
	serviceService := service.New(userUseCase)
	app := NewApp(serviceService)
	return app, func() {
	}, nil
}
