// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"demo/internal/biz"
	"demo/internal/data"
	"demo/internal/service"
)

// Injectors from wire.go:

func InitService() (*service.Service, func(), error) {
	redis, cleanup, err := data.NewRedis()
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.New(redis)
	userUseCase := biz.New(userRepo)
	serviceService := service.New(userUseCase)
	return serviceService, func() {
		cleanup()
	}, nil
}
